spring:
  datasource:
    username: yc
    password: yc
    url: jdbc:mysql://47.107.159.185:3306/ptp_app?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name:  com.mysql.cj.jdbc.Driver
    # 此处使用Druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    filters : stat,wall
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  redis:
    database: 1
    host: 192.168.1.120
    port: 6379
    password:


#mybatis是独立节点，需要单独配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ant.ptpapp.entity
  global-config:
    db-config:
      field-strategy: not_null
server:
  port: 8080
  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    #    buffers-per-region: 1024
    direct-buffers: true
  #  tomcat:
  #    uri-encoding: utf-8
  servlet:
    context-path: /

#自定义参数，可以迁移走
token:
  #redis默认过期时间（2小时）(这是自定义的)(毫秒)
  expirationMilliSeconds: 7200000

#微信相关参数
weChat:
  #小程序appid
  appid: wxfab2755a6cd8daab
  #小程序密钥
  secret: 85dc76039c65b6ffcf9839f680a0e874
  #二维码的宽度，单位 px，最小 280px，最大 1280px
  width: 430
  #自动配置线条颜色，如果颜色依然是黑色，则说明不建议配置主色调，默认 false
  autoColor: false
  #是否需要透明底色，为 true 时，生成透明底色的小程序
  isHyaline: false